# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lobo < Formula
  desc "Rent an RTX 5090 on RunPod or Vast.ai and serve Qwen3.5-27B behind an OpenAI-compatible API"
  homepage "https://github.com/1905/lobocode"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1905/lobocode/releases/download/v0.1.0/lobo_darwin_amd64.tar.gz"
      sha256 "e59f9989e727885613360d89f21542db6e4d61fe82c9b656191a2e63e55a1fa5"

      define_method(:install) do
        bin.install "lobo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1905/lobocode/releases/download/v0.1.0/lobo_darwin_arm64.tar.gz"
      sha256 "5b62663d635e854321c68372bd8a13a77e721599b8e236d4ed8f04f5358443d2"

      define_method(:install) do
        bin.install "lobo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1905/lobocode/releases/download/v0.1.0/lobo_linux_amd64.tar.gz"
      sha256 "88244b04633fad993f35b30bf02571841ba58f00c905a846520c3c42f32acd52"
      define_method(:install) do
        bin.install "lobo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1905/lobocode/releases/download/v0.1.0/lobo_linux_arm64.tar.gz"
      sha256 "55e1b41f95584f2f3f97a9a1984d6c7f3ecd15290add7880110a31fba4dfd2f3"
      define_method(:install) do
        bin.install "lobo"
      end
    end
  end

  test do
    system "#{bin}/lobo", "version"
  end
end
