# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rival < Formula
  desc "Dispatch prompts to AI coding agents with session tracking and TUI/web dashboards"
  homepage "https://github.com/1905/rival"
  version "3.33.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1905/rival/releases/download/v3.33.0/rival_darwin_amd64.tar.gz"
      sha256 "6868f6724ed8506580ae4807b2f634aafc37a7b6283174c4c84393870ddeefb7"

      define_method(:install) do
        bin.install "rival"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1905/rival/releases/download/v3.33.0/rival_darwin_arm64.tar.gz"
      sha256 "20a257db3e0165fc88ee98e8e74bc1cb40c8de06254266bbfa5dbce8bff31f28"

      define_method(:install) do
        bin.install "rival"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1905/rival/releases/download/v3.33.0/rival_linux_amd64.tar.gz"
      sha256 "fbb69572fc335603bb2dfd4ff448d9910a0a52d7eae4df15d717efc2434bce07"
      define_method(:install) do
        bin.install "rival"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1905/rival/releases/download/v3.33.0/rival_linux_arm64.tar.gz"
      sha256 "7e37bd55bc7f865ab43beec18c84a7c9f6f5ecfe88ee5904008becb78d578759"
      define_method(:install) do
        bin.install "rival"
      end
    end
  end
end
